name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -e ".[dev]"
      - name: Lint & Type Check
        run: |
          source .venv/bin/activate
          ruff check .
          ruff format --check .
          mypy src
      - name: Test
        run: |
          source .venv/bin/activate
          pytest -q --disable-warnings --maxfail=1